/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import com.example.sort.HeapSort;
import com.example.sort.HybridSort2;
import com.example.sort.MergeSort;
import com.example.sort.QuickSort;

import java.io.*;
import java.util.Arrays;
import java.util.Comparator;
import java.util.function.BiConsumer;

public class App {
    private enum ALGORITHM {
        ARRAYS_SORT(1, "JDK Arrays Sort", Arrays::sort),
        MERGE_SORT(2, "Merge Sort", MergeSort::sort),
        HEAP_SORT(3, "Heap Sort", HeapSort::sort),
        QUICK_SORT(4, "Quick Sort", QuickSort::sort),
        HYBRID_SORT2(5, "Hybrid Sort 2", HybridSort2::sort);

        private final BiConsumer<Integer[], Comparator<Integer>> algorithm;
        private final String name;
        private final int value;

        public BiConsumer<Integer[], Comparator<Integer>> getAlgorithm() {
            return this.algorithm;
        }

        public String getName() {
            return name;
        }

        public int getValue() {
            return this.value;
        }

        ALGORITHM(final int value, final String name, final BiConsumer<Integer[], Comparator<Integer>> algorithm) {
            this.algorithm = algorithm;
            this.name = name;
            this.value = value;
        }
    }

    private static Integer[] createFilledArray(int length) {
        Integer[] a = new Integer[length];

        for (int i = 0; i < length; i++) {
            a[i] = (int) (Math.random() * 500);
        }

        return a;
    }

    private static boolean isArraysEqual(Integer[] a, Integer[] b) {
        return Arrays.compare(a, b) == 0;
    }

    private static ALGORITHM getAlgorithm(String choice) {
        try {
            int value = Integer.parseInt(choice);
            for (ALGORITHM algorithm : ALGORITHM.values()) {
                if (algorithm.getValue() == value) {
                    return algorithm;
                }
            }
        } catch (NumberFormatException e) {
            return null;
        }

        return null;
    }

    private static long sort(OutputStream out, ALGORITHM algorithm, Integer[] a) throws IOException {
        long deltaTime;

        deltaTime = System.currentTimeMillis();
        algorithm.getAlgorithm().accept(a, Integer::compareTo);
        deltaTime = System.currentTimeMillis() - deltaTime;

        println(out, algorithm.getName() + " took " + deltaTime + "ms to complete");

        return deltaTime;
    }

    private static void loop() {
        try (InputStreamReader in = new InputStreamReader(System.in);
             BufferedReader reader = new BufferedReader(in);
             BufferedOutputStream out = new BufferedOutputStream(System.out)) {
            String choice = readChoice(out, reader);

            while (!choice.equals("q")) {
                ALGORITHM algorithm = getAlgorithm(choice);
                if (algorithm == null) {
                    println(out, "Invalid choice\n");
                } else {
                    Integer[] filledArray = createFilledArray(1000000);
                    Integer[] copy1 = Arrays.copyOf(filledArray, filledArray.length);
                    Integer[] copy2 = Arrays.copyOf(filledArray, filledArray.length);
                    Integer[] copy3 = Arrays.copyOf(filledArray, filledArray.length);
                    long deltaTime1, deltaTime2, deltaTime3;
                    boolean isArrayEqual;

                    sort(out, ALGORITHM.ARRAYS_SORT, filledArray);
                    deltaTime1 = sort(out, algorithm, copy1);
                    deltaTime2 = sort(out, algorithm, copy2);
                    deltaTime3 = sort(out, algorithm, copy3);

                    println(out, "The median time of 3 runs is " + medianOf3(deltaTime1, deltaTime2, deltaTime3) + "ms");

                    isArrayEqual = isArraysEqual(filledArray, copy1);

                    if (!isArrayEqual) {
                        throw new RuntimeException("The array sorted by the algorithm does not match the JDK sorted array!");
                    }

                    println(out, "Time to sort sorted array: ");
                    sort(out, ALGORITHM.ARRAYS_SORT, copy3);
                    sort(out, algorithm, copy3);

                    isArrayEqual = isArraysEqual(filledArray, copy1);

                    if (!isArrayEqual) {
                        throw new RuntimeException("The array sorted by the algorithm does not match the JDK sorted array!");
                    }

                    for (int i = 0, j = filledArray.length - 1; i < j; i++, j--) {
                        int tmp = filledArray[i];
                        filledArray[i] = filledArray[j];
                        filledArray[j] = tmp;
                    }

                    copy1 = Arrays.copyOf(filledArray, filledArray.length);

                    println(out, "Time to sort a reversed sorted array:");
                    sort(out, ALGORITHM.ARRAYS_SORT, filledArray);
                    sort(out, algorithm, copy1);
                    println(out);

                    isArrayEqual = isArraysEqual(filledArray, copy1);

                    if (!isArrayEqual) {
                        throw new RuntimeException("The array sorted by the algorithm does not match the JDK sorted array!");
                    }
                }

                choice = readChoice(out, reader);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static long medianOf3(long a1, long a2, long a3) {
        if (a1 < a2) {
            if (a2 < a3) {
                return a2;
            } else {
                if (a1 < a3) {
                    return a3;
                } else {
                    return a1;
                }
            }
        } else {
            if (a2 < a3) {
                if (a1 < a3) {
                    return a1;
                } else {
                    return a3;
                }
            } else {
                return a2;
            }
        }
    }

    private static void print(OutputStream os, String output) throws IOException {
        os.write(output.getBytes());
        os.flush();
    }

    private static void println(OutputStream os) throws IOException {
        os.write("\n".getBytes());
        os.flush();
    }

    private static void println(OutputStream os, String output) throws IOException {
        os.write((output + '\n').getBytes());
        os.flush();
    }

    private static void printMenu(OutputStream out) throws IOException {
        for (ALGORITHM algorithm : ALGORITHM.values()) {
            println(out, algorithm.getValue() + ": " + algorithm.getName());
        }

        print(out, "Enter Choice: ");
    }

    private static String readChoice(OutputStream out, BufferedReader reader) throws IOException {
        String line;

        printMenu(out);
        line = reader.readLine();

        return line;
    }

    public static void main(String[] args) {
        loop();
    }
}
